"""empty message

Revision ID: ae8efd956abe
Revises: 
Create Date: 2024-11-06 10:34:16.089120

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision = 'ae8efd956abe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('area', sa.Float(), nullable=False),
    sa.Column('income', sa.Float(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('existing_plant_existing_plant_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inserttable',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('machineid', sa.Integer(), nullable=True),
    sa.Column('stateid', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('statechange', sa.Integer(), nullable=False),
    sa.Column('unixtime', sa.Integer(), nullable=False),
    sa.Column('extras', sa.String(length=80), nullable=False),
    sa.Column('state', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metaRecord',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('normalName', sa.String(length=80), nullable=False),
    sa.Column('props', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('schema', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('geo_type', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects_project_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wording', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provinces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('income', sa.Float(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sector',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('area', sa.Float(), nullable=False),
    sa.Column('income', sa.Float(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('existing_plant_existing_plant',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('power', sa.Float(), nullable=False),
    sa.Column('nbrOfhouseholds', sa.Integer(), nullable=True),
    sa.Column('powerForProductiveUsed', sa.Float(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('props', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['existing_plant_existing_plant_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if not op.get_bind().dialect.has_index(op.get_bind(), 'existing_plant_existing_plant', 'idx_existing_plant_existing_plant_geom'):
        with op.batch_alter_table('existing_plant_existing_plant', schema=None) as batch_op:
            batch_op.create_index('idx_existing_plant_existing_plant_geom', ['geom'], unique=False, postgresql_using='gist')

    op.create_table('projects_project',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wording', sa.String(length=80), nullable=False),
    sa.Column('plannedPower', sa.Float(), nullable=True),
    sa.Column('plannedPowerForHouseholds', sa.Float(), nullable=True),
    sa.Column('plannedPowerForProductive', sa.Float(), nullable=True),
    sa.Column('nbrHouseholds', sa.Integer(), nullable=True),
    sa.Column('geomCentroid', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('radius', sa.Float(), nullable=False),
    sa.Column('props', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('dataRadius', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['projects_project_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if not op.get_bind().dialect.has_index(op.get_bind(), 'projects_project', 'idx_projects_project_geomCentroid'):
        with op.batch_alter_table('projects_project', schema=None) as batch_op:
            batch_op.create_index('idx_projects_project_geomCentroid', ['geomCentroid'], unique=False, postgresql_using='gist')

    op.create_table('record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uniqKey', sa.String(length=80), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('props', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('otherData', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('deletedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['metaRecord.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if not op.get_bind().dialect.has_index(op.get_bind(), 'record', 'idx_record_geom'):
        with op.batch_alter_table('record', schema=None) as batch_op:
            batch_op.create_index('idx_record_geom', ['geom'], unique=False, postgresql_using='gist')

    op.create_table('territory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('income', sa.Float(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('ins_code', sa.String(length=80), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('props', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('province_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['province_id'], ['provinces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if not op.get_bind().dialect.has_index(op.get_bind(), 'territory', 'idx_territory_geom'):
        with op.batch_alter_table('territory', schema=None) as batch_op:
            batch_op.create_index('idx_territory_geom', ['geom'], unique=False, postgresql_using='gist')

    op.create_table('territory_demand',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('men', sa.Float(), nullable=True),
    sa.Column('dem', sa.Float(), nullable=True),
    sa.Column('dem_ter', sa.Float(), nullable=True),
    sa.Column('territory_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['territory_id'], ['territory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('territory_pop',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('pop', sa.Float(), nullable=False),
    sa.Column('territory_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['territory_id'], ['territory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    #op.drop_table('layer')
    #op.drop_table('spatial_ref_sys')
    #op.drop_table('topology')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    """op.create_table('topology',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('topology_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('precision', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('hasz', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='topology_pkey'),
    sa.UniqueConstraint('name', name='topology_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.create_table('layer',
    sa.Column('topology_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('layer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('schema_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('table_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('feature_column', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('feature_type', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('level', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('child_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['topology_id'], ['topology.id'], name='layer_topology_id_fkey'),
    sa.PrimaryKeyConstraint('topology_id', 'layer_id', name='layer_pkey'),
    sa.UniqueConstraint('schema_name', 'table_name', 'feature_column', name='layer_schema_name_table_name_feature_column_key')
    )"""
    op.drop_table('territory_pop')
    op.drop_table('territory_demand')
    with op.batch_alter_table('territory', schema=None) as batch_op:
        batch_op.drop_index('idx_territory_geom', postgresql_using='gist')

    op.drop_table('territory')
    with op.batch_alter_table('record', schema=None) as batch_op:
        batch_op.drop_index('idx_record_geom', postgresql_using='gist')

    op.drop_table('record')
    with op.batch_alter_table('projects_project', schema=None) as batch_op:
        batch_op.drop_index('idx_projects_project_geomCentroid', postgresql_using='gist')

    op.drop_table('projects_project')
    with op.batch_alter_table('existing_plant_existing_plant', schema=None) as batch_op:
        batch_op.drop_index('idx_existing_plant_existing_plant_geom', postgresql_using='gist')

    op.drop_table('existing_plant_existing_plant')
    op.drop_table('sector')
    op.drop_table('provinces')
    op.drop_table('projects_project_type')
    op.drop_table('metaRecord')
    op.drop_table('inserttable')
    op.drop_table('existing_plant_existing_plant_type')
    op.drop_table('city')
    # ### end Alembic commands ###
