"""empty message

Revision ID: 2cc08a55654a
Revises: a61121bc537c
Create Date: 2025-10-25 14:13:02.007061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cc08a55654a'
down_revision = 'a61121bc537c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('caissiers')
    with op.batch_alter_table('equipements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('denomination', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('carateristique', sa.String(length=100), nullable=True))

    with op.batch_alter_table('postes_de_peage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voie_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'voies', ['voie_id'], ['id'])

    with op.batch_alter_table('quarts_de_travail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poste_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('quarts_de_travail_voie_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'voies', ['poste_id'], ['id'])
        batch_op.drop_column('voie_id')

    with op.batch_alter_table('voies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('denomination', sa.String(length=50), nullable=False))
        batch_op.drop_constraint('voies_poste_id_fkey', type_='foreignkey')
        batch_op.drop_column('poste_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poste_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('voies_poste_id_fkey', 'postes_de_peage', ['poste_id'], ['id'])
        batch_op.drop_column('denomination')

    with op.batch_alter_table('quarts_de_travail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voie_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('quarts_de_travail_voie_id_fkey', 'voies', ['voie_id'], ['id'])
        batch_op.drop_column('poste_id')

    with op.batch_alter_table('postes_de_peage', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('voie_id')

    with op.batch_alter_table('equipements', schema=None) as batch_op:
        batch_op.drop_column('carateristique')
        batch_op.drop_column('denomination')

    op.create_table('caissiers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('identifiant', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('mot_de_passe_hash', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='caissiers_pkey'),
    sa.UniqueConstraint('identifiant', name='caissiers_identifiant_key')
    )
    # ### end Alembic commands ###
