"""empty message

Revision ID: 40cafe2b2b3a
Revises: f784dd5ff239
Create Date: 2025-11-06 10:41:54.871405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40cafe2b2b3a'
down_revision = 'f784dd5ff239'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quarts_de_travail', schema=None) as batch_op:
        batch_op.drop_constraint('quarts_de_travail_versement_id_fkey', type_='foreignkey')
        batch_op.drop_column('versement_id')

    with op.batch_alter_table('versements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quart_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('utilisateur_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'quarts_de_travail', ['quart_id'], ['id'])
        batch_op.create_foreign_key(None, 'utilisateur', ['utilisateur_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('versements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('utilisateur_id')
        batch_op.drop_column('quart_id')

    with op.batch_alter_table('quarts_de_travail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('versement_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('quarts_de_travail_versement_id_fkey', 'versements', ['versement_id'], ['id'])

    # ### end Alembic commands ###
