"""empty message

Revision ID: 4f7e56210bca
Revises: 2cc08a55654a
Create Date: 2025-10-25 14:18:23.229522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f7e56210bca'
down_revision = '2cc08a55654a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quarts_de_travail', schema=None) as batch_op:
        batch_op.drop_constraint('quarts_de_travail_poste_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'postes_de_peage', ['poste_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quarts_de_travail', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('quarts_de_travail_poste_id_fkey', 'voies', ['poste_id'], ['id'])

    # ### end Alembic commands ###
