"""empty message

Revision ID: 54c20ecef7cb
Revises: 40cafe2b2b3a
Create Date: 2025-11-06 10:49:05.858399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54c20ecef7cb'
down_revision = '40cafe2b2b3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=10), nullable=False),
    sa.Column('sign', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('devises')
    # ### end Alembic commands ###
