"""empty message

Revision ID: 54eae8d6a966
Revises: 
Create Date: 2025-10-23 13:45:07.591143

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '54eae8d6a966'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('enregistrement_id', sa.String(length=255), nullable=False),
    sa.Column('nom_table', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('utilisateur',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uniq_key', sa.String(length=80), nullable=True),
    sa.Column('nom', sa.String(length=80), nullable=True),
    sa.Column('post_nom', sa.String(length=80), nullable=True),
    sa.Column('picture', sa.String(length=255), nullable=True),
    sa.Column('prenom', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=80), nullable=True),
    sa.Column('roles', postgresql.ARRAY(sa.String(length=80)), nullable=True),
    sa.Column('other_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('activate_at', sa.DateTime(), nullable=True),
    sa.Column('deactivate_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('utilisateur')
    op.drop_table('photo')
    # ### end Alembic commands ###
