"""empty message

Revision ID: 8d47f76caeee
Revises: 4f7e56210bca
Create Date: 2025-10-25 14:52:55.647390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d47f76caeee'
down_revision = '4f7e56210bca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passage_vehicules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plaque', sa.String(length=50), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passage_vehicules')
    # ### end Alembic commands ###
