"""empty message

Revision ID: 8f6edcd6bb6b
Revises: 54c20ecef7cb
Create Date: 2025-11-06 10:55:08.819529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f6edcd6bb6b'
down_revision = '54c20ecef7cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lignes_reglement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('devise_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'devises', ['devise_id'], ['id'])
        batch_op.drop_column('devise')

    with op.batch_alter_table('tarifs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('devise_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'devises', ['devise_id'], ['id'])
        batch_op.drop_column('devise')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('devise_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'devises', ['devise_id'], ['id'])
        batch_op.drop_column('devise')

    with op.batch_alter_table('versements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('devise_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'devises', ['devise_id'], ['id'])
        batch_op.drop_column('devise')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('versements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('devise', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('devise_id')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('devise', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('devise_id')

    with op.batch_alter_table('tarifs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('devise', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('devise_id')

    with op.batch_alter_table('lignes_reglement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('devise', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('devise_id')

    # ### end Alembic commands ###
