"""empty message

Revision ID: a61121bc537c
Revises: b0924d7624f8
Create Date: 2025-10-25 13:03:17.816729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a61121bc537c'
down_revision = 'b0924d7624f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fichiers_reglement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('utilisateur_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'utilisateur', ['utilisateur_id'], ['id'])

    with op.batch_alter_table('quarts_de_travail', schema=None) as batch_op:
        batch_op.drop_constraint('quarts_de_travail_caissier_id_fkey', type_='foreignkey')
        batch_op.drop_column('caissier_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quarts_de_travail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caissier_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('quarts_de_travail_caissier_id_fkey', 'caissiers', ['caissier_id'], ['id'])

    with op.batch_alter_table('fichiers_reglement', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('utilisateur_id')

    # ### end Alembic commands ###
