"""empty message

Revision ID: b0924d7624f8
Revises: fa9c9f610b16
Create Date: 2025-10-25 12:44:03.307966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0924d7624f8'
down_revision = 'fa9c9f610b16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quarts_de_travail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('utilisateur_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'utilisateur', ['utilisateur_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quarts_de_travail', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('utilisateur_id')

    # ### end Alembic commands ###
