"""empty message

Revision ID: cbf81e754b19
Revises: 2921f545ecc9
Create Date: 2025-11-06 15:54:58.998763

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cbf81e754b19'
down_revision = '2921f545ecc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passage_vehicules')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passage_vehicules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('plaque', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name='passage_vehicules_transaction_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='passage_vehicules_pkey')
    )
    # ### end Alembic commands ###
