"""empty message

Revision ID: e91919a7cbd2
Revises: 54eae8d6a966
Create Date: 2025-10-23 14:10:14.826032

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e91919a7cbd2'
down_revision = '54eae8d6a966'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caissiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('identifiant', sa.String(length=150), nullable=False),
    sa.Column('mot_de_passe_hash', sa.String(length=512), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifiant')
    )
    op.create_table('categories_vehicules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('regle', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fichiers_reglement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fournisseur', sa.String(length=255), nullable=False),
    sa.Column('date_fichier', sa.Date(), nullable=False),
    sa.Column('montant_total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('nombre_lignes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('postes_de_peage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('localisation', sa.String(length=512), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tarifs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('devise', sa.String(length=10), nullable=False),
    sa.Column('montant', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('date_debut_validite', sa.Date(), nullable=True),
    sa.Column('date_fin_validite', sa.Date(), nullable=True),
    sa.Column('categorie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categorie_id'], ['categories_vehicules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('immatriculation', sa.String(length=50), nullable=True),
    sa.Column('tag_rfid', sa.String(length=255), nullable=True),
    sa.Column('type_identification', sa.String(length=50), nullable=True),
    sa.Column('categorie_id', sa.Integer(), nullable=True),
    sa.Column('proprietaire', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['categorie_id'], ['categories_vehicules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_rfid')
    )
    with op.batch_alter_table('vehicules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicules_immatriculation'), ['immatriculation'], unique=False)

    op.create_table('voies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('direction', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('poste_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['poste_id'], ['postes_de_peage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('numero_serie', sa.String(length=255), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=True),
    sa.Column('derniere_communication', sa.DateTime(), nullable=True),
    sa.Column('voie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['voie_id'], ['voies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_serie')
    )
    op.create_table('quarts_de_travail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('heure_ouverture', sa.DateTime(), nullable=True),
    sa.Column('heure_fermeture', sa.DateTime(), nullable=True),
    sa.Column('fond_ouverture', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('montant_cloture', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('voie_id', sa.Integer(), nullable=False),
    sa.Column('caissier_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['caissier_id'], ['caissiers.id'], ),
    sa.ForeignKeyConstraint(['voie_id'], ['voies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('montant', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('devise', sa.String(length=10), nullable=False),
    sa.Column('moyen_paiement', sa.String(length=50), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=True),
    sa.Column('plaque', sa.String(length=50), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_confirmation', sa.DateTime(), nullable=True),
    sa.Column('reference_externe', sa.String(length=255), nullable=True),
    sa.Column('quart_id', sa.Integer(), nullable=True),
    sa.Column('voie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quart_id'], ['quarts_de_travail.id'], ),
    sa.ForeignKeyConstraint(['voie_id'], ['voies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_reference_externe'), ['reference_externe'], unique=False)

    op.create_table('evenements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('donnees', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('hash_precedent', sa.String(length=128), nullable=True),
    sa.Column('hash_actuel', sa.String(length=128), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lignes_reglement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_externe', sa.String(length=255), nullable=False),
    sa.Column('montant', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('statut', sa.String(length=50), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('fichier_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fichier_id'], ['fichiers_reglement.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fichier_id', 'reference_externe', name='uq_fichier_reference')
    )
    with op.batch_alter_table('lignes_reglement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lignes_reglement_reference_externe'), ['reference_externe'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lignes_reglement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lignes_reglement_reference_externe'))

    op.drop_table('lignes_reglement')
    op.drop_table('evenements')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_reference_externe'))

    op.drop_table('transactions')
    op.drop_table('quarts_de_travail')
    op.drop_table('equipements')
    op.drop_table('voies')
    with op.batch_alter_table('vehicules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicules_immatriculation'))

    op.drop_table('vehicules')
    op.drop_table('tarifs')
    op.drop_table('postes_de_peage')
    op.drop_table('fichiers_reglement')
    op.drop_table('categories_vehicules')
    op.drop_table('caissiers')
    # ### end Alembic commands ###
