"""empty message

Revision ID: fa9c9f610b16
Revises: e91919a7cbd2
Create Date: 2025-10-25 12:37:39.627410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa9c9f610b16'
down_revision = 'e91919a7cbd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fournisseurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('identifiant', sa.String(length=150), nullable=False),
    sa.Column('mot_de_passe_hash', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifiant')
    )
    with op.batch_alter_table('fichiers_reglement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fournisseur_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'fournisseurs', ['fournisseur_id'], ['id'])
        batch_op.drop_column('fournisseur')

    with op.batch_alter_table('lignes_reglement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lignes_reglement', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('fichiers_reglement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fournisseur', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fournisseur_id')

    op.drop_table('fournisseurs')
    # ### end Alembic commands ###
